# Generated by Django 5.0.7 on 2024-08-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product_delete_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
