# Generated by Django 5.0.7 on 2024-08-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_stock_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
