# Generated by Django 5.0.7 on 2024-08-20 19:43

import core.models
import django.db.models.deletion
import django_resized.forms
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'კალათა', 'verbose_name_plural': 'კალათა'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'კატეგორია', 'verbose_name_plural': 'კატეგორიები'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'შეკვეთა', 'verbose_name_plural': 'შეკვეთები'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'შეკვეთის ნივთი', 'verbose_name_plural': 'შეკვეთის ნივთები'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'შეკვეთის სტატუსი', 'verbose_name_plural': 'შეკვეთის სტატუსები'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'პროდუქტი', 'verbose_name_plural': 'პროდუქტები'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.product', verbose_name='პროდუქტი'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='რაოდენობა'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='დამატებითი ინფორმაცია'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150, verbose_name='მისამართი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=150, verbose_name='ქალაქი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='მიწოდების თარიღი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_schedule',
            field=models.CharField(max_length=16, verbose_name='მიწოდების განრიგი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(max_length=150, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(max_length=150, verbose_name='გვარი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_order_status', to='core.orderstatus', verbose_name='შეკვეთის სტატუსი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payed_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='გადახდის თარიღი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_payment_status', to='core.orderstatus', verbose_name='გადახდის სტატუსი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=150, verbose_name='ტელეფონი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='რეგიონი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='second_address',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='მისამართი 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='სრული ღირებულება'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.order', verbose_name='შეკვეთა'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='თანხა'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.product', verbose_name='პროდუქტი'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='რაოდენობა'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='title',
            field=models.CharField(max_length=150, verbose_name='სათაური'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='core.category', verbose_name='კატეგორიები'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='აღწერა'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ფასდაკლებული ფასი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=90, scale=None, size=[960, None], upload_to=functools.partial(core.models.wrapper, *(), **{'target': 'products'}), verbose_name='სურათი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='ლინკი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='სათაური'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი'),
        ),
    ]
